management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      failure-rate-threshold: 99

resilience4j.retry:
  configs:
    default:
      max-retry-attempts: 99

resilience4j.bulkhead:
  configs:
    default:
      max-concurrent-calls: 99

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      max-thread-pool-size: 99

resilience4j.ratelimiter:
  configs:
    default:
      limit-for-period: 99
